### ISSUE TITLE
multiple parent_ids where only one is expected

### ISSUE THREAD

**Issue by horst-n** [ryancramerdesign/DynamicRoles#11]
I think I have found an issue. I get two error messages:

```Notice: Array to string conversion in /www/htdocs/w012f278/aki.nogajski.de/wire/core/PageFinder.php on line 1344```

```Warning: preg_match() expects parameter 2 to be string, array given in /www/htdocs/w012f278/aki.nogajski.de/wire/core/Sanitizer.php on line 328```

The line 1344 in PageFinder is:  ```if(!ctype_digit("$parent_id")) {``` and a check with ```var_dump($parent_id)``` in line 1343 shows ```array(2) { [0]=> string(4) "1121" [1]=> string(4) "1014" }```.

And the line 328 in Sanitizer belongs to ```public function path($value, $maxLength = 1024) {``` and $value here is the same Array with the two ids.

-----------

I get this with a single dynamic role that I have setup with 2 'has_parent' with OR condition:
```  template=50|44, has_parent=1121|1014, status=unpublished  ```

**Comment by ryancramerdesign** [comment]
PW PageFinder hasn't supported multi-value has_parent selectors in the past. However, I just updated it to add support, so it'll appear in this week's core updates.
