### ISSUE TITLE
Not compatible with 3.x

### ISSUE THREAD

**Issue by ivangretsky** [ryancramerdesign/DynamicRoles#19]
Good day!
This super-module seems not to be compatible with 3.x branch. Could it be fixed easily?

**Comment by LostKobrakai** [comment]
It should be wit this one: https://github.com/ryancramerdesign/DynamicRoles/commit/ce7a13b603674bfe0da291e4cd0a05da60462c46

**Comment by ivangretsky** [comment]
Yep. Read the news, but still did not tried it. Anyway probably enough evidence to count it as solved.
